### ISSUE TITLE
Investigate strange bug

### ISSUE THREAD

**Issue by JunaMeinhold** [anthonysSlab/depot#28]
`
[08/26/2022 08:38:47 PM] [Info] Discord : Discord.Net v3.7.2 (API v9)
[08/26/2022 08:38:47 PM] [Info] Gateway : Connecting
[08/26/2022 08:38:48 PM] [Info] Gateway : Connected
[08/26/2022 08:38:51 PM] [Error] Database : fail: 8/26/2022 22:38:51.349 RelationalEventId.CommandError[20102] (Microsoft.EntityFrameworkCore.Database.Command)
      Failed executing DbCommand (0ms) [Parameters=[@__p_0='?' (DbType = Int64), @__p_1='?' (DbType = Int64)], CommandType='Text', CommandTimeout='30']
      SELECT `t`.`Id`, `t`.`GuildId`, `t`.`Ignored`, `g`.`UserId`, `g`.`GuildId`, `t`.`RolesId`, `t`.`UsersUserId`, `t`.`UsersGuildId`, `t0`.`RolesId`, `t0`.`UsersUserId`, `t0`.`UsersGuildId`, `t0`.`UserId`, `t0`.`GuildId`, `t0`.`ActivityWarn`, `t0`.`HasActivityWarn`, `t0`.`LastActivity`
      FROM `GuildUsers` AS `g`
      INNER JOIN (
          SELECT `r`.`Id`, `r`.`GuildId`, `r`.`Ignored`, `g0`.`RolesId`, `g0`.`UsersUserId`, `g0`.`UsersGuildId`
          FROM `GuildUserRole` AS `g0`
          INNER JOIN `Roles` AS `r` ON `g0`.`RolesId` = `r`.`Id`
      ) AS `t` ON (`g`.`UserId` = `t`.`UsersUserId`) AND (`g`.`GuildId` = `t`.`UsersGuildId`)
      LEFT JOIN (
          SELECT `g1`.`RolesId`, `g1`.`UsersUserId`, `g1`.`UsersGuildId`, `g2`.`UserId`, `g2`.`GuildId`, `g2`.`ActivityWarn`, `g2`.`HasActivityWarn`, `g2`.`LastActivity`
          FROM `GuildUserRole` AS `g1`
          INNER JOIN `GuildUsers` AS `g2` ON (`g1`.`UsersUserId` = `g2`.`UserId`) AND (`g1`.`UsersGuildId` = `g2`.`GuildId`)
          WHERE (`g2`.`UserId` = @__p_0) AND (`g2`.`GuildId` = @__p_1)
      ) AS `t0` ON `t`.`Id` = `t0`.`RolesId`
      WHERE (`g`.`UserId` = @__p_0) AND (`g`.`GuildId` = @__p_1)
      ORDER BY `g`.`UserId`, `g`.`GuildId`, `t`.`RolesId`, `t`.`UsersUserId`, `t`.`UsersGuildId`, `t`.`Id`, `t0`.`RolesId`, `t0`.`UsersUserId`, `t0`.`UsersGuildId`, `t0`.`UserId`
[08/26/2022 08:38:51 PM] [Error] Database : fail: 8/26/2022 22:38:51.354 CoreEventId.QueryIterationFailed[10100] (Microsoft.EntityFrameworkCore.Query)
      An exception occurred while iterating over the results of a query for context type 'Depot.Contexts.SystemContext'.
      System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
         at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
[08/26/2022 08:38:51 PM] [Warning] Gateway : A MessageReceived handler has thrown an unhandled exception.
[08/26/2022 08:38:51 PM] [Error] Database : fail: 8/26/2022 22:38:51.360 CoreEventId.QueryIterationFailed[10100] (Microsoft.EntityFrameworkCore.Query)
      An exception occurred while iterating over the results of a query for context type 'Depot.Contexts.SystemContext'.
      System.InvalidOperationException: This MySqlConnection is already in use. See https://fl.vu/mysql-conn-reuse
         at MySqlConnector.Core.ServerSession.StartQuerying(ICancellableCommand command) in /_/src/MySqlConnector/Core/ServerSession.cs:line 288
         at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 50
         at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 330
         at MySqlConnector.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior) in /_/src/MySqlConnector/MySqlCommand.cs:line 272
         at System.Data.Common.DbCommand.ExecuteReader()
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(Enumerator enumerator)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.<>c.<MoveNext>b__19_0(DbContext _, Enumerator enumerator)
         at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
[08/26/2022 08:38:51 PM] [Warning] Gateway : A Ready handler has thrown an unhandled exception.
[08/26/2022 08:38:51 PM] [Info] Gateway    : Ready
[08/26/2022 08:38:57 PM] [Info] Audit : Executing command '!play https://www.youtube.com/watch?v=5wb5HWVh6Fs' for '⁦Juna⁩#2002' in 'music' in 'Server from UwU'
[08/26/2022 08:38:57 PM] [Error] Command         :
[08/26/2022 08:38:57 PM] [Info] Audit : Executed command '!play https://www.youtube.com/watch?v=5wb5HWVh6Fs' for '⁦Juna⁩#2002' in 'music' in 'Server from UwU'`

**Comment by JunaMeinhold** [comment]
Can't reproduce issue any more
